name: Deploy tamilarasu.dev to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies 
        run: pip3 install boto3 requests

      - name: Deploy 
        run: python3 $GITHUB_WORKSPACE/deploy_aws.py
        env: 
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Test
        run: python3 $GITHUB_WORKSPACE/test.py
