name: Deploy tamilarasu.dev to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Boto3
        run: pip3 install boto3

      - uses: nick-invision@assert-action@v1
        with:
          expected: HTTP/2 200
          actual: ${{ curl -I https://www.tamilarasu.dev }}
          comparison: startsWith
